language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="https://www.djangoproject.com/download/1.7b3/tarball/"
  - DJANGO="django==1.6.3"
  - DJANGO="django==1.5.7"
  - DJANGO="django==1.4.12"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django==1.4.12"
    - python: "3.4"
      env: DJANGO="django==1.4.12"

install:
  - pip install $DJANGO --use-mirrors
  - pip install jinja2 django-pipeline --use-mirrors
script:
  - python runtests.py

notifications:
  email:
    recipients:
      - niwi@niwi.be
    on_success: change
    on_failure: change
